-- MySQL Script generated by MySQL Workbench
-- Wed Mar 22 15:16:11 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Schedule`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Schedule` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Schedule` (
  `Schedule_Id` VARCHAR(20) NOT NULL,
  `Days` VARCHAR(45) NULL,
  `DocStartTime` DATETIME NULL,
  `Description` VARCHAR(45) NULL,
  `Doc_Name` VARCHAR(45) NULL,
  `DocBreakTime` DATETIME NULL,
  `DocEndTime` VARCHAR(45) NULL,
  PRIMARY KEY (`Schedule_Id`),
  UNIQUE INDEX `Schedule_Id_UNIQUE` (`Schedule_Id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Admin`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Admin` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Admin` (
  `Admin_ID` INT NOT NULL,
  `Admin_Name` VARCHAR(45) NULL,
  `Admin_Loc` VARCHAR(45) NULL,
  `Admin_Description` VARCHAR(45) NULL,
  PRIMARY KEY (`Admin_ID`),
  UNIQUE INDEX `Admin_ID_UNIQUE` (`Admin_ID` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Doctor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Doctor` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Doctor` (
  `Doc_Id` VARCHAR(20) NOT NULL,
  `Doc_Name` VARCHAR(45) NOT NULL,
  `Doc_Contact` VARCHAR(45) NOT NULL,
  `Doc_Email` VARCHAR(45) NOT NULL,
  `Specialty` VARCHAR(45) NULL,
  `Doc_Pass` VARCHAR(45) NOT NULL,
  `Schedule_Schedule_Id` VARCHAR(20) NOT NULL,
  `Admin_Admin_ID` INT NOT NULL,
  PRIMARY KEY (`Doc_Id`),
  UNIQUE INDEX `Doc_Id_UNIQUE` (`Doc_Id` ASC) VISIBLE,
  UNIQUE INDEX `Doc_Pass_UNIQUE` (`Doc_Pass` ASC) VISIBLE,
  INDEX `fk_Doctor_Schedule_idx` (`Schedule_Schedule_Id` ASC) VISIBLE,
  INDEX `fk_Doctor_Admin1_idx` (`Admin_Admin_ID` ASC) VISIBLE,
  CONSTRAINT `fk_Doctor_Schedule`
    FOREIGN KEY (`Schedule_Schedule_Id`)
    REFERENCES `mydb`.`Schedule` (`Schedule_Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Doctor_Admin1`
    FOREIGN KEY (`Admin_Admin_ID`)
    REFERENCES `mydb`.`Admin` (`Admin_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Patient`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Patient` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Patient` (
  `Patient_ID` VARCHAR(20) NOT NULL,
  `First_Name` VARCHAR(45) NULL,
  `Last_Name` VARCHAR(45) NULL,
  `Pat_Email` VARCHAR(45) NULL,
  `Pat_Contact` VARCHAR(45) NULL,
  `Pat_Pass` VARCHAR(45) NULL,
  PRIMARY KEY (`Patient_ID`),
  UNIQUE INDEX `Patient_ID_UNIQUE` (`Patient_ID` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Appointment`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Appointment` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Appointment` (
  `Appoint_ID` VARCHAR(20) NOT NULL,
  `Appoint_Time` DATETIME NULL,
  `Appoint_Description` VARCHAR(45) NULL,
  `Doctor_Doc_Id` VARCHAR(20) NOT NULL,
  `Patient_Patient_ID` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`Appoint_ID`),
  UNIQUE INDEX `Appoint_ID_UNIQUE` (`Appoint_ID` ASC) VISIBLE,
  INDEX `fk_Appointment_Doctor1_idx` (`Doctor_Doc_Id` ASC) VISIBLE,
  INDEX `fk_Appointment_Patient1_idx` (`Patient_Patient_ID` ASC) VISIBLE,
  CONSTRAINT `fk_Appointment_Doctor1`
    FOREIGN KEY (`Doctor_Doc_Id`)
    REFERENCES `mydb`.`Doctor` (`Doc_Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Appointment_Patient1`
    FOREIGN KEY (`Patient_Patient_ID`)
    REFERENCES `mydb`.`Patient` (`Patient_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
